<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%food_order_type_item}}".
 *
 * @property int $food_order_item_id
 * @property int $order_id
 * @property int $order_type_id
 * @property int|null $food_id
 * @property int $quantity
 * @property float|null $price
 * @property float|null $total
 *
 * @property Food $food
 * @property FoodOrderType $orderType
 */
class FoodOrderTypeItem extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%food_order_type_item}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['food_id', 'quantity'], 'required'],
            [['order_type_id', 'food_id', 'quantity'], 'integer'],
            [['price', 'total'], 'number'],
            [['food_id'], 'exist', 'skipOnError' => true, 'targetClass' => Food::className(), 'targetAttribute' => ['food_id' => 'id']],
            [['order_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => FoodOrderType::className(), 'targetAttribute' => ['order_type_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Food Order Item ID',
            'order_id' => 'Order ID',
            'order_type_id' => 'Order Type ID',
            'food_id' => 'Страва',
            'quantity' => 'Кіл-ть',
            'price' => 'Price',
            'total' => 'Total',

            'apartment_id' => 'Садиба',
            'order_type' => 'Трапеза',
            'serve_at' => 'Час подання',
            'customer_id' => 'Клієнт',
        ];
    }

    /**
     * Gets query for [[Food]].
     *
     * @return \yii\db\ActiveQuery|\common\models\query\FoodQuery
     */
    public function getFood()
    {
        return $this->hasOne(Food::class, ['id' => 'food_id']);
    }

    public function getOrder()
    {
        return $this->hasOne(FoodOrder::class, ['id' => 'order_id']);
    }

    /**
     * Gets query for [[OrderType]].
     *
     * @return \yii\db\ActiveQuery|\common\models\query\FoodOrderTypeQuery
     */
    public function getOrderType()
    {
        return $this->hasOne(FoodOrderType::class, ['id' => 'order_type_id']);
    }

    /**
     * Gets query for [[OrderType]].
     *
     * @return \yii\db\ActiveQuery|\common\models\query\FoodOrderTypeQuery
     */
    /*public function getOrderTypeWithOrder()
    {
        return $this->hasOne(FoodOrderType::class, ['food_order_type_id' => 'order_type_id'])->joinWith('orderWithApartment');
    }*/

    public function beforeSave($insert)
    {
        $food = Food::find()->select(['price'])->where(['id'=>$this->food_id])->one();
        $this->price = $food->price * 2;
        $this->total = $this->quantity * $food->price;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     * @return \common\models\query\FoodOrderTypeItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\FoodOrderTypeItemQuery(get_called_class());
    }
}
